apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-board-pvc
spec:
  storageClassName: hx
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "140Gi"
  volumeName: "message-board-pv"
