apiVersion: v1
kind: PersistentVolume
metadata:
  name: message-board-pv
spec:
  storageClassName: hx
  capacity:
    storage: 140Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "hyperflex/hxvolume"
    fsType: "ext4"
    options:
      hyperflex.io/volumeid: "lunfile_1"
