apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-db-pvc
spec:
  storageClassName: hx
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "140Gi"
  volumeName: "voting-app-db-pv"
